import * as core from '@actions/core'
import * as exec from '@actions/exec'
import * as github from '@actions/github'
import { promises as fs } from 'node:fs'
import os from 'node:os'
import path from 'node:path'

type Mode = 'check' | 'sync'

/**
 * Build a pluginpack source repo for one target and reconcile the generated
 * managed files against a published output repo.
 *
 * - Always diffs a fresh build against the output repo.
 * - `check` mode fails the job when the output is stale (the guard the output
 *   repos run to keep hand-edits out).
 * - `sync` mode builds into a checkout of the output repo, commits to a
 *   machine-owned branch, force-pushes that branch, and opens or updates a PR.
 *   It never pushes to the output repo's base branch.
 */
export async function run(): Promise<void> {
  try {
    const target = core.getInput('target', { required: true })
    const outputRepo = core.getInput('output-repo', { required: true })
    const outputRef = core.getInput('output-ref') || 'main'
    const token = core.getInput('token', { required: true })
    const mode = (core.getInput('mode') || 'sync') as Mode
    const version = core.getInput('pluginpack-version') || 'latest'
    const workingDirectory = core.getInput('working-directory') || '.'
    const branchPrefix = core.getInput('pr-branch-prefix') || 'pluginpack/sync'
    const labels = (core.getInput('pr-labels') || 'pluginpack-sync')
      .split(',')
      .map((label) => label.trim())
      .filter(Boolean)

    if (mode !== 'check' && mode !== 'sync') {
      throw new Error(`mode must be "check" or "sync", got "${mode}"`)
    }
    const [owner, repo] = outputRepo.split('/')
    if (!owner || !repo) {
      throw new Error(`output-repo must be "owner/name", got "${outputRepo}"`)
    }

    // Mask the token so it can't leak through git's command echo.
    core.setSecret(token)

    const spec = `@gleanwork/pluginpack@${version}`
    const branch = `${branchPrefix}-${target}`

    // 1. Check out the output repo into a temp dir.
    const outDir = await fs.mkdtemp(
      path.join(os.tmpdir(), `pluginpack-${target}-`)
    )
    const remote = `https://x-access-token:${token}@github.com/${owner}/${repo}.git`
    await git(['clone', '--depth', '1', '--branch', outputRef, remote, outDir])

    // 2. Diff a fresh build of this target against the output repo.
    const diffCode = await exec.exec(
      'npx',
      ['-y', spec, 'diff', '--target', target, '--against', outDir],
      { cwd: workingDirectory, ignoreReturnCode: true }
    )
    if (diffCode === 0) {
      core.info(`${target}: ${outputRepo} is up to date.`)
      core.setOutput('stale', 'false')
      return
    }
    core.info(`${target}: ${outputRepo} differs from a fresh build.`)
    core.setOutput('stale', 'true')

    if (mode === 'check') {
      core.setFailed(
        `${outputRepo} is stale for target "${target}". Run pluginpack-action in sync mode to update it.`
      )
      return
    }

    // 3. Build the generated output directly into the output-repo checkout.
    await exec.exec(
      'npx',
      ['-y', spec, 'build', '--target', target, '--out-dir', outDir],
      { cwd: workingDirectory }
    )

    // 4. Commit on a machine-owned sync branch and force-push it (never the base).
    await git(['-C', outDir, 'switch', '-C', branch])
    await git(['-C', outDir, 'add', '-A'])
    const status = await gitOutput(['-C', outDir, 'status', '--porcelain'])
    if (!status.trim()) {
      core.info('Build produced no changes; nothing to sync.')
      return
    }

    const { owner: srcOwner, repo: srcRepo } = github.context.repo
    const source = `${srcOwner}/${srcRepo}@${github.context.sha}`
    await git([
      '-C',
      outDir,
      '-c',
      'user.name=pluginpack-action[bot]',
      '-c',
      'user.email=pluginpack-action@users.noreply.github.com',
      'commit',
      '-m',
      `chore: sync ${target} plugins from ${srcOwner}/${srcRepo}\n\nGenerated by pluginpack-action from ${source}.`
    ])
    await git(['-C', outDir, 'push', '--force', 'origin', branch])

    // 5. Open or update the PR. Never push to the base branch directly.
    const octokit = github.getOctokit(token)
    const title = `pluginpack: sync ${target} plugins`
    const body = prBody(target, source, status)

    const existing = await octokit.rest.pulls.list({
      owner,
      repo,
      head: `${owner}:${branch}`,
      base: outputRef,
      state: 'open'
    })

    let prNumber: number
    let prUrl: string
    if (existing.data.length > 0) {
      prNumber = existing.data[0].number
      prUrl = existing.data[0].html_url
      await octokit.rest.pulls.update({
        owner,
        repo,
        pull_number: prNumber,
        title,
        body
      })
      core.info(`Updated PR #${prNumber}: ${prUrl}`)
    } else {
      const created = await octokit.rest.pulls.create({
        owner,
        repo,
        head: branch,
        base: outputRef,
        title,
        body
      })
      prNumber = created.data.number
      prUrl = created.data.html_url
      core.info(`Opened PR #${prNumber}: ${prUrl}`)
    }

    if (labels.length > 0) {
      await octokit.rest.issues.addLabels({
        owner,
        repo,
        issue_number: prNumber,
        labels
      })
    }

    core.setOutput('pr-number', String(prNumber))
    core.setOutput('pr-url', prUrl)
  } catch (error) {
    if (error instanceof Error) core.setFailed(error.message)
  }
}

/** Build a PR body summarizing the change set from `git status --porcelain`. */
function prBody(target: string, source: string, porcelain: string): string {
  const lines = porcelain.split('\n').filter(Boolean)
  const added = lines.filter((l) => l[0] === 'A' || l.startsWith('??')).length
  const modified = lines.filter((l) => l[0] === 'M' || l[1] === 'M').length
  const removed = lines.filter((l) => l[0] === 'D' || l[1] === 'D').length
  const fileList = lines
    .slice(0, 50)
    .map((l) => `- \`${l.trim()}\``)
    .join('\n')
  const more = lines.length > 50 ? `\n…and ${lines.length - 50} more.` : ''
  return [
    `Generated by [pluginpack-action](https://github.com/gleanwork/pluginpack-action) for target \`${target}\`.`,
    '',
    `Source: \`${source}\``,
    '',
    `**Changes:** ${added} added, ${modified} changed, ${removed} removed.`,
    '',
    '<details><summary>Files</summary>',
    '',
    fileList + more,
    '',
    '</details>',
    '',
    '> This branch is machine-owned and force-updated on each sync. Do not push to it by hand.'
  ].join('\n')
}

async function git(args: string[]): Promise<void> {
  await exec.exec('git', args)
}

async function gitOutput(args: string[]): Promise<string> {
  let out = ''
  await exec.exec('git', args, {
    listeners: { stdout: (data: Buffer) => (out += data.toString()) }
  })
  return out
}
